### ISSUE TITLE
Grupo

### ISSUE THREAD

**Issue by Caldeiradas** [nleite-isel/ave-2018-19-sem1-li41n#1]
[Rolfest](https://github.com/Rolfest) - 38478 - Fernando Duarte  
[PiniponSelvagem](https://github.com/PiniponSelvagem) - 41429 - Rodrigo Silva 
[Caldeiradas](https://github.com/Caldeiradas) - 41465 - Gonçalo Caldeira

**Comment by nleite-isel** [comment]
Obrigado.

**Comment by Caldeiradas** [comment]
Bom dia!  
Há algum problema com a criação deste grupo?
