### ISSUE TITLE
Grupo 14

### ISSUE THREAD

**Issue by Diogomorais** [nleite-isel/ave-2018-19-sem1-li41n#5]
Boa noite,

Pode adicionar pff ao repositório do grupo 14, LI41N:

Diogo Morais - @DiogoMorais - 40583

Obrigado

**Comment by nleite-isel** [comment]
Viva,
O convite já tinha sido enviado anteriormente quando criei o repositório. Deves ver o email e aceitar o convite.

**Comment by Diogomorais** [comment]
Não encontro mail a convidar-me para o grupo no meu email associado ao Git

**Comment by nleite-isel** [comment]
OK, já está. O anterior convite era do prof. Miguel Carvalho.
